window.SPOTRA_CONFIG = {
  SUPABASE_URL: '',
  SUPABASE_ANON_KEY: '',
  GOOGLE_MAPS_API_KEY: '',
  GOOGLE_MAP_ID: '',
  DEFAULT_COUNTRY: 'UY',
  DEFAULT_CENTER: { lat: -34.9011, lng: -56.1645 },
  DEFAULT_ZOOM: 12,
  MOCK_MODE: true
};
